[project]
name = "infoskjerm-karusell"
version = "0.1.0"
description = "Applikasjon for infoskjermer i A6"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyautogui>=0.9.54",
    "pyyaml>=6.0.2",
]